// <auto-generated />
using System;
using Kaaiman_reizen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaaiman_reizen.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260430140407_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.AvailabilityPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("AvailabilityPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateOnly(2026, 7, 31),
                            Start = new DateOnly(2026, 4, 1),
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 2,
                            End = new DateOnly(2026, 5, 31),
                            Start = new DateOnly(2026, 3, 1),
                            TravelLeaderId = 2
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<int>("Busses")
                        .HasColumnType("int");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RequiredLeaders")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.Property<int>("Travelers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Journey");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingStatus = 0,
                            Busses = 1,
                            End = new DateOnly(2026, 7, 14),
                            Name = "Italië",
                            RequiredLeaders = 1,
                            Start = new DateOnly(2026, 7, 1),
                            Travelers = 10
                        },
                        new
                        {
                            Id = 2,
                            BookingStatus = 0,
                            Busses = 2,
                            End = new DateOnly(2026, 3, 20),
                            Name = "Spanje",
                            RequiredLeaders = 1,
                            Start = new DateOnly(2026, 3, 10),
                            Travelers = 15
                        },
                        new
                        {
                            Id = 3,
                            BookingStatus = 1,
                            Busses = 1,
                            End = new DateOnly(2026, 4, 3),
                            Name = "Oostenrijk",
                            RequiredLeaders = 1,
                            Start = new DateOnly(2026, 3, 25),
                            Travelers = 8
                        },
                        new
                        {
                            Id = 4,
                            BookingStatus = 2,
                            Busses = 3,
                            End = new DateOnly(2026, 4, 15),
                            Name = "Griekenland",
                            RequiredLeaders = 2,
                            Start = new DateOnly(2026, 4, 5),
                            Travelers = 25
                        },
                        new
                        {
                            Id = 5,
                            BookingStatus = 2,
                            Busses = 2,
                            End = new DateOnly(2026, 5, 10),
                            Name = "Kroatië",
                            RequiredLeaders = 1,
                            Start = new DateOnly(2026, 4, 28),
                            Travelers = 12
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.JourneyTravelLeader", b =>
                {
                    b.Property<int>("JourneyId")
                        .HasColumnType("int")
                        .HasColumnName("JourneysId");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int")
                        .HasColumnName("TravelLeadersId");

                    b.HasKey("JourneyId", "TravelLeaderId");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("JourneyTravelLeaders");

                    b.HasData(
                        new
                        {
                            JourneyId = 2,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            JourneyId = 3,
                            TravelLeaderId = 1
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PlanningAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("PlanningVersionId")
                        .HasColumnType("int");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("PlanningVersionId");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("PlanningAssignments");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PlanningVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PlanningYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlanningVersions");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("PreferredDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Italië",
                            Rank = 1,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Griekenland",
                            Rank = 2,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Kroatië",
                            Rank = 3,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Spanje",
                            Rank = 1,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 5,
                            Destination = "Oostenrijk",
                            Rank = 2,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Destination = "Griekenland",
                            Rank = 3,
                            TravelLeaderId = 2
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Rule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reisleider mag geen overlappende reizen hebben.",
                            IsActive = true,
                            Key = "NoOverlap"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minimaal aantal dagen tussen twee reizen.",
                            IsActive = true,
                            Key = "MinimumGapDays",
                            Value = "3"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Minimaal aantal reizen ervaring voor niet-standaard bestemmingen.",
                            IsActive = true,
                            Key = "RequiredExperience",
                            Value = "3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Controle op minimum/maximum aantal reizen per reisleider.",
                            IsActive = true,
                            Key = "MinMaxJourneys"
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfTrips")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxTrips")
                        .HasColumnType("int");

                    b.Property<int>("MinTrips")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TravelLeader");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfTrips = 8,
                            IsActive = true,
                            MaxTrips = 10,
                            MinTrips = 2,
                            Name = "Jan de Vries",
                            Note = "",
                            PhoneNumber = "06-12345678"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfTrips = 12,
                            IsActive = true,
                            MaxTrips = 15,
                            MinTrips = 3,
                            Name = "Maria Jansen",
                            Note = "",
                            PhoneNumber = "06-87654321"
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.AvailabilityPeriod", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany("AvailabilityPeriods")
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.JourneyTravelLeader", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.Journey", "Journey")
                        .WithMany()
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany()
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.Notification", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PlanningAssignment", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.Journey", "Journey")
                        .WithMany()
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kaaiman_reizen.Data.Entities.PlanningVersion", "PlanningVersion")
                        .WithMany("Assignments")
                        .HasForeignKey("PlanningVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany()
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("PlanningVersion");

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany("PreferredDestinations")
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaaiman_reizen.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PlanningVersion", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Navigation("AvailabilityPeriods");

                    b.Navigation("PreferredDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
