// <auto-generated />
using System;
using Kaaiman_reizen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaaiman_reizen.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260318122546_AddTravelLeaderIsActive")]
    partial class AddTravelLeaderIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.AvailabilityPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("AvailabilityPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateOnly(2025, 5, 3),
                            Start = new DateOnly(2025, 4, 29),
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 2,
                            End = new DateOnly(2025, 6, 14),
                            Start = new DateOnly(2025, 5, 30),
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 3,
                            End = new DateOnly(2025, 12, 31),
                            Start = new DateOnly(2025, 1, 1),
                            TravelLeaderId = 2
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("PreferredDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Italië",
                            Rank = 1,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Griekenland",
                            Rank = 2,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Kroatië",
                            Rank = 3,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Spanje",
                            Rank = 1,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 5,
                            Destination = "Portugal",
                            Rank = 2,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Destination = "Marokko",
                            Rank = 3,
                            TravelLeaderId = 2
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfTrips")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxTrips")
                        .HasColumnType("int");

                    b.Property<int>("MinTrips")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TravelLeader");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfTrips = 8,
                            IsActive = true,
                            MaxTrips = 0,
                            MinTrips = 0,
                            Name = "Jan de Vries",
                            Note = "",
                            PhoneNumber = "06-12345678"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfTrips = 12,
                            IsActive = true,
                            MaxTrips = 0,
                            MinTrips = 0,
                            Name = "Maria Jansen",
                            Note = "",
                            PhoneNumber = "06-87654321"
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.AvailabilityPeriod", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany("AvailabilityPeriods")
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany("PreferredDestinations")
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Navigation("AvailabilityPeriods");

                    b.Navigation("PreferredDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
