// <auto-generated />
using Kaaiman_reizen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaaiman_reizen.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TravelLeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelLeaderId");

                    b.ToTable("PreferredDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Italië",
                            Rank = 1,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Griekenland",
                            Rank = 2,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Kroatië",
                            Rank = 3,
                            TravelLeaderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Spanje",
                            Rank = 1,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 5,
                            Destination = "Portugal",
                            Rank = 2,
                            TravelLeaderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Destination = "Marokko",
                            Rank = 3,
                            TravelLeaderId = 2
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfTrips")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhenAvailable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TravelLeader");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfTrips = 8,
                            Name = "Jan de Vries",
                            PhoneNumber = "06-12345678",
                            WhenAvailable = "April–juni 2025"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfTrips = 12,
                            Name = "Maria Jansen",
                            PhoneNumber = "06-87654321",
                            WhenAvailable = "Hele jaar"
                        });
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.PreferredDestination", b =>
                {
                    b.HasOne("Kaaiman_reizen.Data.Entities.TravelLeader", "TravelLeader")
                        .WithMany("PreferredDestinations")
                        .HasForeignKey("TravelLeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelLeader");
                });

            modelBuilder.Entity("Kaaiman_reizen.Data.Entities.TravelLeader", b =>
                {
                    b.Navigation("PreferredDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
